### PR TITLE
Broadcast Addresses details

### PR DESCRIPTION
**Pull request by mostorer**
Within Commands.md some details about Broadcast Address creation and mean have been added just after the Type + Sub Type section

### CODE REVIEW

**Comment by Pascal66** [comment]
There's 16 broadcast addresses.
Those are only specific to Velux

**Comment by mostorer** [comment]
> There's 16 broadcast addresses.
> Those are only specific to only 2W ON/OFF devices, like things with a little motor with returned Infos.
> Good catch

I can't understand what you mean.
My analysis has been done on 1W Velux controllers and devices and, after implementing the 1W controller in sw, tested in real world and that's it.
For devices other than Velux, I cannot say anything.

**Comment by Velocet** [comment]
As @Pascal66 said: The commands.md needs to be split cause there is way too much information in it.

My plan would be to keep the commands.md only really for the commands ids and copy information about parsing into another document including links between the two.

**Comment by Velocet** [comment]
> > There's 16 broadcast addresses.
> > Those are only specific to only 2W ON/OFF devices, like things with a little motor with returned Infos.
> > Good catch
> 
> I can't understand what you mean. My analysis has been done on 1W Velux controllers and devices and, after implementing the 1W controller in sw, tested in real world and that's it. For devices other than Velux, I cannot say anything.

1W/2W is not only different in regards to the used encryption/auth method but also in the handling of the protocol itself:
As per iohc documentation every device has to have at least a basic stock of commands it needs to understand. Those correlate directly to RTS commands and is the reason you can use a simple Velux 1W remote (like KLI31x) with Somfy blinds. Same goes for 2W but it is always tied to a ManufacturerID which defines additional commands/data.

**Review by Velocet — APPROVED** [review]

**Pull request merged**
